### ISSUE TITLE
UI tesztek készítése

### ISSUE THREAD

**Issue by martinjkab** [BME-MIT-IET/iet-hf-2023-integracios-es-ellenorzesi-technikak#2]

**Comment by martinjkab** [comment]
600e1b8e0964590de40f5e8c8e015b6843ee1337 - Menüablak tesztelése
195f5f05de89e3393e7ce13cf9212fae908bc9f6 - A fő játékablak tesztelése
87c9ba81013d16bbd97bfe84080da7426ff64e7a - Dokumentáció elkészítése

**Comment by scsng** [comment]
191c588 - átültettem a keretrendszerbe
228ef0a  - megoldottam az eddig kapott NullpointerException hibát a fest-util konyvár implementálásával
