### ISSUE TITLE
Egységtesztek írása + tesztkészlet bővítése

### ISSUE THREAD

**Issue by jakymatyas** [BME-MIT-IET/iet-hf-2023-integracios-es-ellenorzesi-technikak#3]

**Comment by scsng** [comment]
#9 kész

**Comment by jahudak** [comment]
Javítottam, hogy korábban nem voltam hozzá-assignolva az Issue-hoz.

**Comment by jahudak** [comment]
Teszt prototípusok fcbf0d2
Ezen a ponton teljesen átdolgoztuk a teszteket
Move, Collect tesztek d76f7ea
Use, Rob tesztek b9ae370
Folyamatosan ellenőriztük a tesztlefedettséget
Kisebb módosítások történtek a végén

**Comment by scsng** [comment]
Néhány mappa bent marad ezt töröltam a #12 commitban, és mergeltem is.
