### ISSUE TITLE
Manuális tesztelés

### ISSUE THREAD

**Issue by jakymatyas** [BME-MIT-IET/iet-hf-2023-integracios-es-ellenorzesi-technikak#4]

**Comment by jahudak** [comment]
Javítottam, hogy korábban nem voltam hozzá-assignolva az Issue-hoz.

**Comment by MartinKing01** [comment]
#ef4966a73e937b1bd1e30778ed97c397335f4aa6

**Comment by MartinKing01** [comment]
ef4966a73e937b1bd1e30778ed97c397335f4aa6

**Comment by jahudak** [comment]
Egységes teszt váz elkészítése abd5aec
Részletes tesztesetek elkészítése 7d277eb
Dokumentáció 35b6080
Dokumentáció módosítások 5669386
Dokumentáció elkészült 0cb300b
